#pragma once

#define WT_WS_VISIBLE 1
#define WT_WS_MAXIMIZABLE 2
#define WT_WS_MINIMIZABLE 4
#define WT_WS_CLOSABLE 8
#define WT_WS_ACTIVE 16

#define WT_INPUT_EVENT_MOUSE 1
#define WT_INPUT_EVENT_KEY 2

#define WT_MOUSE_EVENT_PRESS 1
#define WT_MOUSE_EVENT_RELEASE 2
#define WT_MOUSE_EVENT_MOVE 3
#define WT_MOUSE_EVENT_DRAG 4
#define WT_MOUSE_EVENT_WHEEL_UP 5
#define WT_MOUSE_EVENT_WHEEL_DOWN 6

#define WT_MOUSE_BUTTON_NONE 0
#define WT_MOUSE_BUTTON_RIGHT 1
#define WT_MOUSE_BUTTON_LEFT 2
#define WT_MOUSE_BUTTON_MIDDLE 3

#define WT_KEY_EVENT_PRESS 1
#define WT_KEY_EVENT_RELEASE 2
#define WT_KEY_EVENT_TEXT 3
